# Generated by Django 4.0.2 on 2022-02-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('_class', models.IntegerField()),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('school', models.IntegerField()),
                ('_timestamp', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
            ],
        ),
    ]
